### ISSUE TITLE
Please come in

### ISSUE THREAD

**Issue by dnknn** [kpion/inzoom#11]
Outdated

**Comment by kpion** [comment]
Wow, thank you very much for this! I can see you put a lot of work in this! 

I will sit back to this project very soon, right now I work like 14h a day on something else, but in a week I should be done with it, and will make the improvements.

Thanks again!

**Comment by dnknn** [comment]
@kpion Hi, Can you understand the meaning of **a picture opened in a new tab**
I think it should be well supported, this will be a very useful highlight.
