### ISSUE TITLE
2 suggestions for enhancement/improvement !

### ISSUE THREAD

**Issue by dnknn** [kpion/inzoom#12]
<details>
<summary>Details</summary>

Hi, inzoom is great, but I make 2 suggestions for enhancement/improvement.

- ### add a ⚙ : &ensp;⬜ `double-clicking` (⚠Only for images, not videos) can also to **reset** zoom/drag?

> can double-clicking to reset image is more in line with the mouse operation and faster.

![0710011959](https://user-images.githubusercontent.com/10995302/87070516-7e912a80-c24b-11ea-9dd8-42d991e0803c.png)

---

- ## When `Esc` to reset;  then remove `.inzoom-draggable` **event** completely

![208_09162036](https://user-images.githubusercontent.com/10995302/89728020-4d7b6400-da5c-11ea-8c6b-a286c6b59afd.png)

This change will be **again** **restored**  the browser own dragging behavior of the image element, It will be very convenient..
Because some browsers support the super dragging behavior of the mouse. For example, [֎CentBrowserᐝ](http://centbrowser.com/)

In other words, when Esc to reset,  will not be able to directly dragging-move,
if want to dragging-move, you must be re-zoom 👇

<details>
<summary>Details</summary>

> after you zoom in/out an element, this element becomes "draggable", so you can move it around in its container
![208_09164417](https://user-images.githubusercontent.com/10995302/89728387-941e8d80-da5f-11ea-9e72-90ecae2e667e.png)

</details>

<details>
<summary>Details see gif demo</summary>

![208_09162854](https://user-images.githubusercontent.com/10995302/89728119-6f291b00-da5d-11ea-86c7-019f9ec76497.png)

![drag](https://user-images.githubusercontent.com/10995302/89728231-55d49e80-da5e-11ea-9642-ef5c1e2820eb.gif)

</details>

---

### ※Recommend powerful tools for independent tab/window image viewer !
- ### [Viewhance](https://chrome.google.com/webstore/detail/impppjchnpfgknmbaaghfeopcgfoilac)		&emsp; author of `Imagus`.  
&emsp;&emsp; &emsp; Can use the `wheel` to zoom directly and many other functions .
&emsp;&emsp; &emsp; https://drive.google.com/drive/folders/0Bx8fnUCX4W2IOTdESEFoM3luS1U
&emsp;&emsp; &emsp; https://github.com/Deathamns/Viewhance

- ### https://greasyfork.org/scripts/16403
&emsp;&emsp; &emsp; Can show image attribute info 
&emsp;&emsp; &emsp; Can use <kbd>Esc</kbd> to quickly close the image tab

- ### Compatible with other extension, see at Deathamns/Viewhance/issues/70

</details>

**Comment by kpion** [comment]
HI  @dnknn, sorry for the late answer, first I was busy, then I got Covid 19 :( 

Thank you very much for the ideas, I hope to get back to the project in about 2 or three weeks and I'll try to handle them.
